/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Login;

import Doctor.Doctor;
import Pharmacy.Pharmacy;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Sinem
 */
public class Login extends javax.swing.JFrame {
 int attempt = 0;
    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jtxtUsername = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jPassword = new javax.swing.JPasswordField();
        jbtnLogin = new javax.swing.JButton();
        jbtnExit = new javax.swing.JButton();
        jbtnCancel = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jbtnPatient = new javax.swing.JButton();
        jbtnDoctor = new javax.swing.JButton();
        jbtnPayment = new javax.swing.JButton();
        jbtnPharmacy = new javax.swing.JButton();
        jbtnGPAppointment = new javax.swing.JButton();
        jbtnPharmacyOffice = new javax.swing.JButton();
        jbtnSpecialist = new javax.swing.JButton();
        jbtnSurgery = new javax.swing.JButton();
        jbtnConsultant = new javax.swing.JButton();
        jbtnHospital = new javax.swing.JButton();
        jbtnPharmacist = new javax.swing.JButton();
        jbtnHelp = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(153, 0, 0));
        jLabel7.setText("UserName:");

        jtxtUsername.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jtxtUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtUsernameActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(153, 0, 0));
        jLabel8.setText("Password:");

        jPassword.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordActionPerformed(evt);
            }
        });

        jbtnLogin.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbtnLogin.setForeground(new java.awt.Color(153, 0, 0));
        jbtnLogin.setText(" Login");
        jbtnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnLoginActionPerformed(evt);
            }
        });

        jbtnExit.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbtnExit.setForeground(new java.awt.Color(153, 0, 0));
        jbtnExit.setText("Exit");
        jbtnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnExitActionPerformed(evt);
            }
        });

        jbtnCancel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbtnCancel.setForeground(new java.awt.Color(153, 0, 0));
        jbtnCancel.setText("Cancel");
        jbtnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCancelActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 0, 0));
        jLabel2.setText("Login Systems");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jbtnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jtxtUsername)
                            .addComponent(jPassword, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jbtnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                        .addComponent(jbtnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(66, 66, 66))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(179, 179, 179)
                .addComponent(jLabel2)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 200, 610, 350));

        jbtnPatient.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jbtnPatient.setText("Patient");
        jbtnPatient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnPatientActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnPatient, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 310, 240, -1));

        jbtnDoctor.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jbtnDoctor.setText("Doctor");
        jbtnDoctor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnDoctorActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnDoctor, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 190, 240, -1));

        jbtnPayment.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jbtnPayment.setText("Payment");
        jbtnPayment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnPaymentActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnPayment, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 380, 240, -1));

        jbtnPharmacy.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jbtnPharmacy.setText("Pharmacy");
        jbtnPharmacy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnPharmacyActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnPharmacy, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 250, 240, -1));

        jbtnGPAppointment.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jbtnGPAppointment.setText("GPAppointment");
        jbtnGPAppointment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnGPAppointmentActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnGPAppointment, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 450, 240, -1));

        jbtnPharmacyOffice.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jbtnPharmacyOffice.setText("Pharmacy Office");
        jbtnPharmacyOffice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnPharmacyOfficeActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnPharmacyOffice, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 520, 240, -1));

        jbtnSpecialist.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jbtnSpecialist.setText("Specialist");
        getContentPane().add(jbtnSpecialist, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 310, 240, -1));

        jbtnSurgery.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jbtnSurgery.setText("Surgery");
        jbtnSurgery.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSurgeryActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnSurgery, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 190, 240, -1));

        jbtnConsultant.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jbtnConsultant.setText("Consultant");
        getContentPane().add(jbtnConsultant, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 380, 240, -1));

        jbtnHospital.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jbtnHospital.setText("Hospital");
        jbtnHospital.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnHospitalActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnHospital, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 250, 240, -1));

        jbtnPharmacist.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jbtnPharmacist.setText("Pharmacist");
        jbtnPharmacist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnPharmacistActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnPharmacist, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 450, 240, -1));

        jbtnHelp.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jbtnHelp.setText("Help");
        getContentPane().add(jbtnHelp, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 520, 240, -1));

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 0, 0));
        jLabel1.setText("Pharmacy Management Systems");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(jLabel1)
                .addContainerGap(64, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel1)
                .addContainerGap(48, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 0, 920, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnLoginActionPerformed
        String Username = jtxtUsername.getText();
         String Password = jPassword.getText();
         
         if (Username.contains("one")&& (Password.contains("one")))
         {
             jtxtUsername.setText("");
             jPassword.setText("");
               jbtnDoctor.setEnabled(true);
        jbtnPharmacy.setEnabled(true);
        
jbtnPatient.setEnabled(true);
jbtnPayment.setEnabled(true);
jbtnGPAppointment.setEnabled(true);
jbtnPharmacyOffice.setEnabled(true);
jbtnSurgery.setEnabled(true);
jbtnHospital.setEnabled(true);
jbtnSpecialist.setEnabled(true);
jbtnConsultant.setEnabled(true);
jbtnPharmacist.setEnabled(true);
jbtnHelp.setEnabled(true);
        
         }  
         else if (!(Username.contains("one")&& (Password.contains("one"))))
         {
             jtxtUsername.setText("");
             jPassword.setText("");
             jbtnDoctor.setEnabled(false);
             jbtnPharmacy.setEnabled(false);
        
             jbtnPatient.setEnabled(false);
             jbtnPayment.setEnabled(false);
             jbtnGPAppointment.setEnabled(false);
             jbtnPharmacyOffice.setEnabled(false);
             jbtnSurgery.setEnabled(false);
             jbtnHospital.setEnabled(false);
             jbtnSpecialist.setEnabled(false);
             jbtnConsultant.setEnabled(false);
             jbtnPharmacist.setEnabled(false);
             jbtnHelp.setEnabled(false);
             attempt +=1;
             
             if(attempt ==3)
             {
                 System.exit(0);
             }    
             
        
         }
    }//GEN-LAST:event_jbtnLoginActionPerformed
private JFrame frame;
    private void jbtnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnExitActionPerformed
       
        frame = new JFrame("Exit");
        if (JOptionPane.showConfirmDialog(frame, "Confirm if you want to exit","Pharmacy Management Systems",
               JOptionPane.YES_NO_OPTION) ==JOptionPane.YES_NO_OPTION){
            System.exit(0);
        }
    }//GEN-LAST:event_jbtnExitActionPerformed

    private void jbtnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCancelActionPerformed
       jtxtUsername.setText("");
       jPassword.setText(""); 
    }//GEN-LAST:event_jbtnCancelActionPerformed

    private void jbtnPharmacyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPharmacyActionPerformed
       Pharmacy myPharmacy = new Pharmacy();
       myPharmacy.setVisible(true);
    }//GEN-LAST:event_jbtnPharmacyActionPerformed

    private void jbtnHospitalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnHospitalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnHospitalActionPerformed

    private void jbtnPharmacistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPharmacistActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnPharmacistActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        
        jbtnDoctor.setEnabled(false);
        jbtnPharmacy.setEnabled(false);
        
jbtnPatient.setEnabled(false);
jbtnPayment.setEnabled(false);
jbtnGPAppointment.setEnabled(false);
jbtnPharmacyOffice.setEnabled(false);
jbtnSurgery.setEnabled(false);
jbtnHospital.setEnabled(false);
jbtnSpecialist.setEnabled(false);
jbtnConsultant.setEnabled(false);
jbtnPharmacist.setEnabled(false);
jbtnHelp.setEnabled(false);
        
        
    }//GEN-LAST:event_formWindowActivated

    private void jbtnPaymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPaymentActionPerformed
         Doctor iDoctor = new Doctor(); 
            iDoctor.setVisible(true);
    }//GEN-LAST:event_jbtnPaymentActionPerformed

    private void jbtnSurgeryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSurgeryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnSurgeryActionPerformed

    private void jtxtUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtUsernameActionPerformed
        jtxtUsername.setText("");
    }//GEN-LAST:event_jtxtUsernameActionPerformed

    private void jPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordActionPerformed
         // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordActionPerformed

    private void jbtnDoctorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDoctorActionPerformed
       Doctor iDoctor = new Doctor(); 
            iDoctor.setVisible(true);
    }//GEN-LAST:event_jbtnDoctorActionPerformed

    private void jbtnPatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPatientActionPerformed
      Pharmacy iPharmacy = new Pharmacy(); 
            iPharmacy.setVisible(true);
    }//GEN-LAST:event_jbtnPatientActionPerformed

    private void jbtnGPAppointmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnGPAppointmentActionPerformed
        Pharmacy iPharmacy = new Pharmacy(); 
            iPharmacy.setVisible(true);
    }//GEN-LAST:event_jbtnGPAppointmentActionPerformed

    private void jbtnPharmacyOfficeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPharmacyOfficeActionPerformed
         Doctor iDoctor = new Doctor(); 
            iDoctor.setVisible(true);
    }//GEN-LAST:event_jbtnPharmacyOfficeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField jPassword;
    private javax.swing.JButton jbtnCancel;
    private javax.swing.JButton jbtnConsultant;
    private javax.swing.JButton jbtnDoctor;
    private javax.swing.JButton jbtnExit;
    private javax.swing.JButton jbtnGPAppointment;
    private javax.swing.JButton jbtnHelp;
    private javax.swing.JButton jbtnHospital;
    private javax.swing.JButton jbtnLogin;
    private javax.swing.JButton jbtnPatient;
    private javax.swing.JButton jbtnPayment;
    private javax.swing.JButton jbtnPharmacist;
    private javax.swing.JButton jbtnPharmacy;
    private javax.swing.JButton jbtnPharmacyOffice;
    private javax.swing.JButton jbtnSpecialist;
    private javax.swing.JButton jbtnSurgery;
    private javax.swing.JTextField jtxtUsername;
    // End of variables declaration//GEN-END:variables
}
