/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Doctor;

import javax.swing.JFrame;
import Login.Login;
import Pharmacy.Pharmacy;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Sinem
 */
public class Doctor extends javax.swing.JFrame {
    
     
     private JFrame frame;
    /**
     * Creates new form Doctor
     */
    public Doctor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jxtDose = new javax.swing.JLabel();
        jxFirstname = new javax.swing.JTextField();
        jxtNumberofTablets = new javax.swing.JLabel();
        jxSurname = new javax.swing.JTextField();
        jxtLOT = new javax.swing.JLabel();
        jxMedCentreName = new javax.swing.JTextField();
        jxtIssuedDate = new javax.swing.JLabel();
        jxPatientID1 = new javax.swing.JTextField();
        jxtExpDate = new javax.swing.JLabel();
        jxAdressofCentre = new javax.swing.JTextField();
        jxtDailyDose = new javax.swing.JLabel();
        jxPostCode = new javax.swing.JTextField();
        jxtStorageAdvice = new javax.swing.JLabel();
        jxOfficePhoneNo2 = new javax.swing.JTextField();
        jxtAdministration = new javax.swing.JLabel();
        jxFaxNo = new javax.swing.JTextField();
        jxtDrivingandUsingMachines = new javax.swing.JLabel();
        jxmail = new javax.swing.JTextField();
        jxtHowtoUseMedication = new javax.swing.JLabel();
        jxPatientNHS = new javax.swing.JTextField();
        jxtPatientID = new javax.swing.JLabel();
        jxEMISNumber = new javax.swing.JTextField();
        jxtDoctorsNHSNo = new javax.swing.JLabel();
        jxGPAppRef = new javax.swing.JTextField();
        jxtPossibleSideEffects = new javax.swing.JLabel();
        jxMedCentreRef = new javax.swing.JTextField();
        jxtFurtherInformation = new javax.swing.JLabel();
        jxOfficePhoneNo1 = new javax.swing.JTextField();
        jxtNameofTablets = new javax.swing.JLabel();
        jxtReferenceNo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jtbnDelete = new javax.swing.JButton();
        jxPharmacy = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jbtnExit = new javax.swing.JButton();
        jxDocNHSNo = new javax.swing.JTextField();
        jxDocRefNo = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1400, 3800));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jxtDose.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jxtDose.setText("Firstname:");
        getContentPane().add(jxtDose, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, -1, 30));

        jxFirstname.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jxFirstname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jxFirstnameActionPerformed(evt);
            }
        });
        getContentPane().add(jxFirstname, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 150, 230, 30));

        jxtNumberofTablets.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jxtNumberofTablets.setText("Surname:");
        getContentPane().add(jxtNumberofTablets, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, -1, 30));

        jxSurname.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(jxSurname, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 200, 230, 30));

        jxtLOT.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jxtLOT.setText("Medical Centre Name:");
        getContentPane().add(jxtLOT, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, 200, 30));

        jxMedCentreName.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(jxMedCentreName, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 250, 230, 30));

        jxtIssuedDate.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jxtIssuedDate.setText("Patient ID:");
        getContentPane().add(jxtIssuedDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 300, -1, 30));

        jxPatientID1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(jxPatientID1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 300, 230, 30));

        jxtExpDate.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jxtExpDate.setText("Adress of Centre:");
        getContentPane().add(jxtExpDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 350, -1, 30));

        jxAdressofCentre.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(jxAdressofCentre, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 350, 230, 30));

        jxtDailyDose.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jxtDailyDose.setText("Post Code:");
        getContentPane().add(jxtDailyDose, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 400, -1, 30));

        jxPostCode.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(jxPostCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 400, 230, 30));

        jxtStorageAdvice.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jxtStorageAdvice.setText("Office Phone No 2:");
        getContentPane().add(jxtStorageAdvice, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 150, 210, 30));

        jxOfficePhoneNo2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(jxOfficePhoneNo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 150, 260, 30));

        jxtAdministration.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jxtAdministration.setText("Fax No:");
        getContentPane().add(jxtAdministration, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 200, 210, 30));

        jxFaxNo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(jxFaxNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 200, 260, 30));

        jxtDrivingandUsingMachines.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jxtDrivingandUsingMachines.setText("Email Adress:");
        getContentPane().add(jxtDrivingandUsingMachines, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 250, 280, 30));

        jxmail.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(jxmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 250, 260, 30));

        jxtHowtoUseMedication.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jxtHowtoUseMedication.setText("Patient NHS Number:");
        getContentPane().add(jxtHowtoUseMedication, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 300, 250, 30));

        jxPatientNHS.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(jxPatientNHS, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 300, 260, 30));

        jxtPatientID.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jxtPatientID.setText("EMIS Number:");
        getContentPane().add(jxtPatientID, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 350, 170, 30));

        jxEMISNumber.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(jxEMISNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 350, 260, 30));

        jxtDoctorsNHSNo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jxtDoctorsNHSNo.setText("GP Appointment Ref:");
        getContentPane().add(jxtDoctorsNHSNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 400, 220, 30));

        jxGPAppRef.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(jxGPAppRef, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 400, 260, 30));

        jxtPossibleSideEffects.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jxtPossibleSideEffects.setText("Medical Centre Ref:");
        getContentPane().add(jxtPossibleSideEffects, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 50, 260, 30));

        jxMedCentreRef.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(jxMedCentreRef, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 50, 260, 30));

        jxtFurtherInformation.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jxtFurtherInformation.setText("Office Phone No 1:");
        getContentPane().add(jxtFurtherInformation, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 100, 260, 30));

        jxOfficePhoneNo1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(jxOfficePhoneNo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 100, 260, 30));

        jxtNameofTablets.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jxtNameofTablets.setText("Doctor's Ref No:");
        getContentPane().add(jxtNameofTablets, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, 160, 30));

        jxtReferenceNo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jxtReferenceNo.setText("Doctor's NHS No:");
        getContentPane().add(jxtReferenceNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, -1, 30));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Doctors'Ref No", "Doctor's NHS No", "Firstname", "Surname", "Medical Centre Name", "Patient ID", "Adress of Centre", "Post Code", "Medical Centre Ref", "Office Phone No1", "Office Phone No2", "Fax No", "Email Adress", "Patient NHS Number", "EMIS Bumber", "GP Appointment Ref"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 510, 1140, 290));

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 102, 204));
        jButton1.setText("Payment");

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 102, 204));
        jButton2.setText("GP Appointment");

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(0, 102, 204));
        jButton3.setText("Update");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton4.setForeground(new java.awt.Color(0, 102, 204));
        jButton4.setText("Doctor");

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton5.setForeground(new java.awt.Color(0, 102, 204));
        jButton5.setText("Patient");

        jtbnDelete.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtbnDelete.setForeground(new java.awt.Color(0, 102, 204));
        jtbnDelete.setText("Delete");
        jtbnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtbnDeleteActionPerformed(evt);
            }
        });

        jxPharmacy.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jxPharmacy.setForeground(new java.awt.Color(0, 102, 204));
        jxPharmacy.setText("Pharmacy");
        jxPharmacy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jxPharmacyActionPerformed(evt);
            }
        });

        jButton8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton8.setForeground(new java.awt.Color(0, 102, 204));
        jButton8.setText("Login");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jbtnExit.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbtnExit.setForeground(new java.awt.Color(0, 102, 204));
        jbtnExit.setText("Exit");
        jbtnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtbnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jxPharmacy, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbtnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtbnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jxPharmacy, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 450, 1140, 50));

        jxDocNHSNo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jxDocNHSNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jxDocNHSNoActionPerformed(evt);
            }
        });
        getContentPane().add(jxDocNHSNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 100, 230, 30));

        jxDocRefNo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jxDocRefNo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Doctor's Reference", "AK558123", "EC956442", "SD245710", "ZP530780" }));
        jxDocRefNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jxDocRefNoActionPerformed(evt);
            }
        });
        getContentPane().add(jxDocRefNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 50, 230, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jxFirstnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jxFirstnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jxFirstnameActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();

        model.addRow(new Object[]{jxDocRefNo.getSelectedItem().toString(),
            jxDocNHSNo.getText(),jxFirstname.getText(), jxSurname.getText(), jxMedCentreName.getText(),
            jxPatientID1.getText(), jxAdressofCentre.getText(), jxPostCode.getText(),
            jxMedCentreRef.getText(), jxOfficePhoneNo1.getText(), jxOfficePhoneNo2.getText(),
            jxFaxNo.getText(), jxmail.getText(),
            jxPatientNHS.getText(),
            jxEMISNumber.getText(), jxGPAppRef.getText(),});

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jtbnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtbnDeleteActionPerformed
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        if(jTable1.getSelectedRow()==-1){
            if(jTable1.getRowCount()==0){

                JOptionPane.showMessageDialog(null, "No data to delete",
                    "Pharmacy Management System",JOptionPane.OK_OPTION);
            }else{

                JOptionPane.showMessageDialog(null,"Select a row to delete",
                    "Pharmacy Management System",JOptionPane.OK_OPTION);
            }
        }else{
            model.removeRow(jTable1.getSelectedRow());
        }
    }//GEN-LAST:event_jtbnDeleteActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        Login iLogin = new Login();
        iLogin.setVisible(true);
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jbtnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnExitActionPerformed
        frame = new JFrame("Exit");
        if (JOptionPane.showConfirmDialog(frame, "Confirm if you want to exit","Pharmacy Management Systems",
            JOptionPane.YES_NO_OPTION) ==JOptionPane.YES_NO_OPTION){
        System.exit(0);
        }
    }//GEN-LAST:event_jbtnExitActionPerformed

    private void jxDocNHSNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jxDocNHSNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jxDocNHSNoActionPerformed

    private void jxPharmacyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jxPharmacyActionPerformed
            Pharmacy iPharmacy = new Pharmacy(); 
            iPharmacy.setVisible(true);
    }//GEN-LAST:event_jxPharmacyActionPerformed

    private void jxDocRefNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jxDocRefNoActionPerformed
        if (jxDocRefNo.getSelectedItem().equals("AK558123"))
        {
            
        
             jxDocNHSNo.setText("Dr678532");
            jxFirstname.setText("Hasan");
            jxSurname.setText("Anderson");
            jxMedCentreName.setText("Yakacık Medical Center");
            jxPatientID1.setText("2457371");
            jxAdressofCentre.setText("12 Yakacık Carsı");
            jxPostCode.setText("3400");

            jxMedCentreRef.setText("YKC85441");
            jxOfficePhoneNo1.setText("021644130267");
            jxOfficePhoneNo2.setText("021644130267");
            jxFaxNo.setText("021644130268");
            jxmail.setText("Ykc.med@gmail.com");
            jxPatientNHS.setText("743560");
            jxEMISNumber.setText("S672080");
            jxGPAppRef.setText("Yes");

        }
        else if(jxDocRefNo.getSelectedItem().equals("EC956442"))
        {
            jxDocNHSNo.setText("Dr694512");
            jxFirstname.setText("Ece");
            jxSurname.setText("Tok");
            jxMedCentreName.setText("Yakacık Medical Center");
            jxPatientID1.setText("2457371");
            jxAdressofCentre.setText("12 Yakacık Carsı");
            jxPostCode.setText("3400");

            jxMedCentreRef.setText("YKC85441");
            jxOfficePhoneNo1.setText("021644130262");
            jxOfficePhoneNo2.setText("021644130266");
            jxFaxNo.setText("020544130268");
            jxmail.setText("Tok.med@gmail.com");
            jxPatientNHS.setText("493513");
            jxEMISNumber.setText("S678880");
            jxGPAppRef.setText("Yes");
            
        }
         
        else if(jxDocRefNo.getSelectedItem().equals("SD245710"))
        {
            jxDocNHSNo.setText("Dr494022");
            jxFirstname.setText("Cem");
            jxSurname.setText("Akkan");
            jxMedCentreName.setText("Yakacık Medical Center");
            jxPatientID1.setText("2467073");
            jxAdressofCentre.setText("12 Yakacık Carsı");
            jxPostCode.setText("3400");

            jxMedCentreRef.setText("YKC85441");
            jxOfficePhoneNo1.setText("021744139263");
            jxOfficePhoneNo2.setText("021744131266");
            jxFaxNo.setText("02244130268");
            jxmail.setText("Akkan.med@gmail.com");
            jxPatientNHS.setText("403513");
            jxEMISNumber.setText("S778980");
            jxGPAppRef.setText("Yes");
             }
        
         
        else if(jxDocRefNo.getSelectedItem().equals("ZP530780"))
         {
            jxDocNHSNo.setText("Dr414057");
            jxFirstname.setText("Baran");
            jxSurname.setText("Evgin");
            jxMedCentreName.setText("Yakacık Medical Center");
            jxPatientID1.setText("2444173");
            jxAdressofCentre.setText("12 Yakacık Carsı");
            jxPostCode.setText("3400");

            jxMedCentreRef.setText("YKC85441");
            jxOfficePhoneNo1.setText("021621139263");
            jxOfficePhoneNo2.setText("021644131266");
            jxFaxNo.setText("01894130268");
            jxmail.setText("Evgın.med@gmail.com");
            jxPatientNHS.setText("893513");
            jxEMISNumber.setText("S078980");
            jxGPAppRef.setText("Yes");
             }
            
    }//GEN-LAST:event_jxDocRefNoActionPerformed

    /*
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Doctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Doctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Doctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Doctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Doctor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton jbtnExit;
    private javax.swing.JButton jtbnDelete;
    private javax.swing.JTextField jxAdressofCentre;
    private javax.swing.JTextField jxDocNHSNo;
    private javax.swing.JComboBox<String> jxDocRefNo;
    private javax.swing.JTextField jxEMISNumber;
    private javax.swing.JTextField jxFaxNo;
    private javax.swing.JTextField jxFirstname;
    private javax.swing.JTextField jxGPAppRef;
    private javax.swing.JTextField jxMedCentreName;
    private javax.swing.JTextField jxMedCentreRef;
    private javax.swing.JTextField jxOfficePhoneNo1;
    private javax.swing.JTextField jxOfficePhoneNo2;
    private javax.swing.JTextField jxPatientID1;
    private javax.swing.JTextField jxPatientNHS;
    private javax.swing.JButton jxPharmacy;
    private javax.swing.JTextField jxPostCode;
    private javax.swing.JTextField jxSurname;
    private javax.swing.JTextField jxmail;
    private javax.swing.JLabel jxtAdministration;
    private javax.swing.JLabel jxtDailyDose;
    private javax.swing.JLabel jxtDoctorsNHSNo;
    private javax.swing.JLabel jxtDose;
    private javax.swing.JLabel jxtDrivingandUsingMachines;
    private javax.swing.JLabel jxtExpDate;
    private javax.swing.JLabel jxtFurtherInformation;
    private javax.swing.JLabel jxtHowtoUseMedication;
    private javax.swing.JLabel jxtIssuedDate;
    private javax.swing.JLabel jxtLOT;
    private javax.swing.JLabel jxtNameofTablets;
    private javax.swing.JLabel jxtNumberofTablets;
    private javax.swing.JLabel jxtPatientID;
    private javax.swing.JLabel jxtPossibleSideEffects;
    private javax.swing.JLabel jxtReferenceNo;
    private javax.swing.JLabel jxtStorageAdvice;
    // End of variables declaration//GEN-END:variables
}
