/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Pharmacy;

import Doctor.Doctor;
import Login.Login;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Sinem
 */
public class Pharmacy extends javax.swing.JFrame {

    /**
     * Creates new form Pharmacy
     */
    public Pharmacy() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jxtDose = new javax.swing.JLabel();
        jxDose = new javax.swing.JTextField();
        jxtNumberofTablets = new javax.swing.JLabel();
        jxNumberofTablets = new javax.swing.JTextField();
        jxtLOT = new javax.swing.JLabel();
        jxLOT = new javax.swing.JTextField();
        jxtIssuedDate = new javax.swing.JLabel();
        jxIssuedDate = new javax.swing.JTextField();
        jxtExpDate = new javax.swing.JLabel();
        jxExpDate = new javax.swing.JTextField();
        jxtDailyDose = new javax.swing.JLabel();
        jxDailyDose = new javax.swing.JTextField();
        jxtStorageAdvice = new javax.swing.JLabel();
        jxStorageAdvice = new javax.swing.JTextField();
        jxtAdministration = new javax.swing.JLabel();
        jxAdministration = new javax.swing.JTextField();
        jxtDrivingandUsingMachines = new javax.swing.JLabel();
        jxDrivingandUsingMachines = new javax.swing.JTextField();
        jxtHowtoUseMedication = new javax.swing.JLabel();
        jxHowtoUseMedication = new javax.swing.JTextField();
        jxtPatientID = new javax.swing.JLabel();
        jxPatientID = new javax.swing.JTextField();
        jxtDoctorsNHSNo = new javax.swing.JLabel();
        jxDoctorsNHSNo = new javax.swing.JTextField();
        jxtPossibleSideEffects = new javax.swing.JLabel();
        jxPossibleSideEffects = new javax.swing.JTextField();
        jxtFurtherInformation = new javax.swing.JLabel();
        jxFurtherInformation = new javax.swing.JTextField();
        jxtNameofTablets = new javax.swing.JLabel();
        jxtReferenceNo = new javax.swing.JLabel();
        jxReferenceNo = new javax.swing.JTextField();
        jxNameTablets = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jtbnDelete = new javax.swing.JButton();
        jxPharmacy = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jbtnExit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jxtDose.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jxtDose.setText("Dose(mg):");
        getContentPane().add(jxtDose, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, -1, 30));

        jxDose.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jxDose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jxDoseActionPerformed(evt);
            }
        });
        getContentPane().add(jxDose, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 150, 230, 30));

        jxtNumberofTablets.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jxtNumberofTablets.setText("Number of Tablets:");
        getContentPane().add(jxtNumberofTablets, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, -1, 30));

        jxNumberofTablets.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(jxNumberofTablets, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 200, 230, 30));

        jxtLOT.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jxtLOT.setText("LOT:");
        getContentPane().add(jxtLOT, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, -1, 30));

        jxLOT.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(jxLOT, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 250, 230, 30));

        jxtIssuedDate.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jxtIssuedDate.setText("Issued Date:");
        getContentPane().add(jxtIssuedDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 300, -1, 30));

        jxIssuedDate.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(jxIssuedDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 300, 230, 30));

        jxtExpDate.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jxtExpDate.setText("Exp Date:");
        getContentPane().add(jxtExpDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 350, -1, 30));

        jxExpDate.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(jxExpDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 350, 230, 30));

        jxtDailyDose.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jxtDailyDose.setText("Daily Dose:");
        getContentPane().add(jxtDailyDose, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 400, -1, 30));

        jxDailyDose.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(jxDailyDose, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 400, 230, 30));

        jxtStorageAdvice.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jxtStorageAdvice.setText("Storage Advice:");
        getContentPane().add(jxtStorageAdvice, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 150, 210, 30));

        jxStorageAdvice.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(jxStorageAdvice, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 150, 260, 30));

        jxtAdministration.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jxtAdministration.setText("Administration:");
        getContentPane().add(jxtAdministration, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 200, 210, 30));

        jxAdministration.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(jxAdministration, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 200, 260, 30));

        jxtDrivingandUsingMachines.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jxtDrivingandUsingMachines.setText("Driving and Using Machines:");
        getContentPane().add(jxtDrivingandUsingMachines, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 250, 280, 30));

        jxDrivingandUsingMachines.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(jxDrivingandUsingMachines, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 250, 260, 30));

        jxtHowtoUseMedication.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jxtHowtoUseMedication.setText("How to Use Medication:");
        getContentPane().add(jxtHowtoUseMedication, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 300, 250, 30));

        jxHowtoUseMedication.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(jxHowtoUseMedication, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 300, 260, 30));

        jxtPatientID.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jxtPatientID.setText("Patient ID:");
        getContentPane().add(jxtPatientID, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 350, 170, 30));

        jxPatientID.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(jxPatientID, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 350, 260, 30));

        jxtDoctorsNHSNo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jxtDoctorsNHSNo.setText("Doctors NHS No:");
        getContentPane().add(jxtDoctorsNHSNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 400, 220, 30));

        jxDoctorsNHSNo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(jxDoctorsNHSNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 400, 260, 30));

        jxtPossibleSideEffects.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jxtPossibleSideEffects.setText("Possible Side Effects:");
        getContentPane().add(jxtPossibleSideEffects, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 50, 260, 30));

        jxPossibleSideEffects.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(jxPossibleSideEffects, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 50, 260, 30));

        jxtFurtherInformation.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jxtFurtherInformation.setText("Further Information:");
        getContentPane().add(jxtFurtherInformation, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 100, 260, 30));

        jxFurtherInformation.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(jxFurtherInformation, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 100, 260, 30));

        jxtNameofTablets.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jxtNameofTablets.setText("Name of Tablets:");
        getContentPane().add(jxtNameofTablets, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, 160, 30));

        jxtReferenceNo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jxtReferenceNo.setText("Reference No:");
        getContentPane().add(jxtReferenceNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, -1, 30));

        jxReferenceNo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jxReferenceNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jxReferenceNoActionPerformed(evt);
            }
        });
        getContentPane().add(jxReferenceNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 100, 230, 30));

        jxNameTablets.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jxNameTablets.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Make a selection", "Ativan", "Codeine", "Naproxen", "Viagra" }));
        jxNameTablets.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jxNameTabletsActionPerformed(evt);
            }
        });
        getContentPane().add(jxNameTablets, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 50, 230, 30));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name of Tablets", "Reference No", "Dose(mg)", "Number of Tablets", "LOT", "Issued Date", "Exp Date", "Daily Dose", "Possible Side Effects", "Further Information", "Storage Advice", "Administration", "Driving and Using Machines", "How to use Meication", "Patient ID", "DoctorsNHSNo"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 510, 1140, 290));

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 102, 204));
        jButton1.setText("Payment");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 102, 204));
        jButton2.setText("GP Appointment");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(0, 102, 204));
        jButton3.setText("Update");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton4.setForeground(new java.awt.Color(0, 102, 204));
        jButton4.setText("Doctor");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton5.setForeground(new java.awt.Color(0, 102, 204));
        jButton5.setText("Patient");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jtbnDelete.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtbnDelete.setForeground(new java.awt.Color(0, 102, 204));
        jtbnDelete.setText("Delete");
        jtbnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtbnDeleteActionPerformed(evt);
            }
        });

        jxPharmacy.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jxPharmacy.setForeground(new java.awt.Color(0, 102, 204));
        jxPharmacy.setText("Pharmacy");
        jxPharmacy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jxPharmacyActionPerformed(evt);
            }
        });

        jButton8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton8.setForeground(new java.awt.Color(0, 102, 204));
        jButton8.setText("Login");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jbtnExit.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbtnExit.setForeground(new java.awt.Color(0, 102, 204));
        jbtnExit.setText("Exit");
        jbtnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtbnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jxPharmacy, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbtnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtbnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jxPharmacy, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 450, 1140, 50));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jxNameTabletsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jxNameTabletsActionPerformed
        if (jxNameTablets.getSelectedItem().equals("Ativan"))         
        {
          
          jxReferenceNo.setText("4");
          jxDose.setText("3");
          jxNumberofTablets.setText("4");
          jxLOT.setText("498551307");
          jxIssuedDate.setText("10/05/2019");
          jxExpDate.setText("8/05/2020");
          jxDailyDose.setText("2");
          
          
          jxPossibleSideEffects.setText("headache");
          jxFurtherInformation.setText("Delivery");
          jxStorageAdvice.setText("Less than 15");
          jxAdministration.setText("Actioned");        
          jxDrivingandUsingMachines.setText("No");
          jxHowtoUseMedication.setText("Drink Water before Eat");        
          jxPatientID.setText("P4672080");       
          jxDoctorsNHSNo.setText("874321");        
             
                  
    
                  
        }
        
         if (jxNameTablets.getSelectedItem().equals("Codeine"))         
        {
          
          jxReferenceNo.setText("3");
          jxDose.setText("2");
          jxNumberofTablets.setText("3");
          jxLOT.setText("498551307");
          jxIssuedDate.setText("10/05/2019");
          jxExpDate.setText("8/05/2020");
          jxDailyDose.setText("2");
          
          
          jxPossibleSideEffects.setText("headache");
          jxFurtherInformation.setText("Delivery");
          jxStorageAdvice.setText("Less than 15");
          jxAdministration.setText("Actioned");        
          jxDrivingandUsingMachines.setText("No");
          jxHowtoUseMedication.setText("Drink Water before Eat");        
          jxPatientID.setText("P4672080");       
          jxDoctorsNHSNo.setText("874321");        
             
                  
    
                  
        }
          if (jxNameTablets.getSelectedItem().equals("Naproxen"))         
        {
          
          jxReferenceNo.setText("4");
          jxDose.setText("3");
          jxNumberofTablets.setText("4");
          jxLOT.setText("498551307");
          jxIssuedDate.setText("10/05/2019");
          jxExpDate.setText("8/05/2020");
          jxDailyDose.setText("2");
          
          
          jxPossibleSideEffects.setText("headache");
          jxFurtherInformation.setText("Delivery");
          jxStorageAdvice.setText("Less than 15");
          jxAdministration.setText("Actioned");        
          jxDrivingandUsingMachines.setText("No");
          jxHowtoUseMedication.setText("Drink Water before Eat");        
          jxPatientID.setText("P4672080");       
          jxDoctorsNHSNo.setText("874321");        
             
                  
    
                  
        }
          if (jxNameTablets.getSelectedItem().equals("Viagra"))         
        {
          
          jxReferenceNo.setText("4");
          jxDose.setText("3");
          jxNumberofTablets.setText("4");
          jxLOT.setText("498551307");
          jxIssuedDate.setText("10/05/2019");
          jxExpDate.setText("8/05/2020");
          jxDailyDose.setText("2");
          
          
          jxPossibleSideEffects.setText("stomache");
          jxFurtherInformation.setText("Delivery");
          jxStorageAdvice.setText("Less than 15");
          jxAdministration.setText("Actioned");        
          jxDrivingandUsingMachines.setText("No");
          jxHowtoUseMedication.setText("Drink Water before Eat");        
          jxPatientID.setText("P4672080");       
          jxDoctorsNHSNo.setText("874321");        
             
                  
    
                  
        }
          
         
    }//GEN-LAST:event_jxNameTabletsActionPerformed

    private void jxDoseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jxDoseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jxDoseActionPerformed

    private void jxReferenceNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jxReferenceNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jxReferenceNoActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
            
      DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
       
       model.addRow(new Object[]{jxNameTablets.getSelectedItem().toString(),
       jxNumberofTablets.getText(),jxReferenceNo.getText(), jxReferenceNo.getText(), jxLOT.getText(), 
     jxIssuedDate.getText(), jxExpDate.getText(), jxDailyDose.getText(),
     jxPossibleSideEffects.getText(), jxFurtherInformation.getText(), jxStorageAdvice.getText(),
     jxAdministration.getText(), jxDrivingandUsingMachines.getText(),
      jxHowtoUseMedication.getText(),
     jxPatientID.getText(), jxDoctorsNHSNo.getText(),}); 
    
     
           
       
           
    }//GEN-LAST:event_jButton3ActionPerformed
    private JFrame frame;
    private void jbtnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnExitActionPerformed
        frame = new JFrame("Exit");
        if (JOptionPane.showConfirmDialog(frame, "Confirm if you want to exit","Pharmacy Management Systems",
               JOptionPane.YES_NO_OPTION) ==JOptionPane.YES_NO_OPTION){
            System.exit(0);
        }
    }//GEN-LAST:event_jbtnExitActionPerformed

    private void jtbnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtbnDeleteActionPerformed
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        if(jTable1.getSelectedRow()==-1){
            if(jTable1.getRowCount()==0){
                
                JOptionPane.showMessageDialog(null, "No data to delete",
                        "Pharmacy Management System",JOptionPane.OK_OPTION);
            }else{
                
                JOptionPane.showMessageDialog(null,"Select a row to delete",
                        "Pharmacy Management System",JOptionPane.OK_OPTION);
            }
        }else{
            model.removeRow(jTable1.getSelectedRow());
        }
    }//GEN-LAST:event_jtbnDeleteActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
       Login iLogin = new Login();
       iLogin.setVisible(true);
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        Doctor iDoctor = new Doctor(); 
            iDoctor.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
         Doctor iDoctor = new Doctor(); 
            iDoctor.setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jxPharmacyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jxPharmacyActionPerformed
       
         Doctor iDoctor = new Doctor(); 
            iDoctor.setVisible(true);
    }//GEN-LAST:event_jxPharmacyActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
         Pharmacy iPharmacy = new Pharmacy(); 
            iPharmacy.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Pharmacy iPharmacy = new Pharmacy(); 
            iPharmacy.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pharmacy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pharmacy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pharmacy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pharmacy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pharmacy().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton jbtnExit;
    private javax.swing.JButton jtbnDelete;
    private javax.swing.JTextField jxAdministration;
    private javax.swing.JTextField jxDailyDose;
    private javax.swing.JTextField jxDoctorsNHSNo;
    private javax.swing.JTextField jxDose;
    private javax.swing.JTextField jxDrivingandUsingMachines;
    private javax.swing.JTextField jxExpDate;
    private javax.swing.JTextField jxFurtherInformation;
    private javax.swing.JTextField jxHowtoUseMedication;
    private javax.swing.JTextField jxIssuedDate;
    private javax.swing.JTextField jxLOT;
    private javax.swing.JComboBox<String> jxNameTablets;
    private javax.swing.JTextField jxNumberofTablets;
    private javax.swing.JTextField jxPatientID;
    private javax.swing.JButton jxPharmacy;
    private javax.swing.JTextField jxPossibleSideEffects;
    private javax.swing.JTextField jxReferenceNo;
    private javax.swing.JTextField jxStorageAdvice;
    private javax.swing.JLabel jxtAdministration;
    private javax.swing.JLabel jxtDailyDose;
    private javax.swing.JLabel jxtDoctorsNHSNo;
    private javax.swing.JLabel jxtDose;
    private javax.swing.JLabel jxtDrivingandUsingMachines;
    private javax.swing.JLabel jxtExpDate;
    private javax.swing.JLabel jxtFurtherInformation;
    private javax.swing.JLabel jxtHowtoUseMedication;
    private javax.swing.JLabel jxtIssuedDate;
    private javax.swing.JLabel jxtLOT;
    private javax.swing.JLabel jxtNameofTablets;
    private javax.swing.JLabel jxtNumberofTablets;
    private javax.swing.JLabel jxtPatientID;
    private javax.swing.JLabel jxtPossibleSideEffects;
    private javax.swing.JLabel jxtReferenceNo;
    private javax.swing.JLabel jxtStorageAdvice;
    // End of variables declaration//GEN-END:variables
}
